export enum EnumCodigoErro {
  MENSAGEM_INVALIDA = 1,
  CREDENCIAIS_INVALIDAS = 2,
  TRANSACAO_INEXISTENTE = 3,
  CODIGO_SEGURANCA_INVALIDO = 8,
  INCONSISTENCIA_ENVIO_CARTAO = 10,
  MODALIDADE_NAO_HABILITADA = 11,
  NUMERO_PARCELAS_INVALIDO = 12 || 22,
  FLAG_AUTORIZACAO_AUTOMATICA = 13,
  AUTORIZACAO_DIRETA_INVALIDA = 14,
  AUTORIZAZAO_DIRETA_SEM_CARTAO = 15,
  IDENTIFICADOR_TID_INVALIDO = 16,
  CODIGO_SEGURANCA_AUSENTE = 17,
  IDENTIFICADOR_CODIGO_SEGURANCA_INCONSISTENTE = 18,
  URL_RETORNO_NAO_INFORMADA = 19,
  STATUS_NAO_PERMITE_AUTORIZACAO = 20,
  PRAZO_AUTORIZACAO_VENCIDO = 21,
  ENCAMINHAMENTO_AUTORIZACAO_NAO_PERMITIDO = 25,
  STATUS_INVALIDO_CAPTURA = 30,
  PRAZO_CAPTURA_VENCIDO = 31,
  VALOR_CAPTURA_INVALIDO = 32,
  FALHA_NA_CAPTURA = 33,
  VALOR_TAXA_EMBARQUE_OBRIGATORIO = 34,
  BANDEIRA_INVALIDA_PARA_UTILIZACAO_TAXA_EMBARQUE = 35,
  PRODUTO_INVALIDO_PARA_UTILIZACAO_TAXA_EMBARQUE = 36,
  PRAZO_CANCELAMENTO_VENCIDO = 40,
  FALHA_NO_CANCELAMENTO = 42,
  VALOR_CANCELAMENTO_MAIOR_QUE_AUTORIZADO = 43,
  RECORRENCIA_INVALIDA = 51,
  TOKEN_INVALIDO = 52,
  RECORRENCIA_NAO_HABILITADA = 53,
  TRANSACAO_COM_TOKEN_INVALIDA = 54,
  NUMERO_CARTAO_NAO_INFORMADO = 55,
  VALIDADE_CARTAO_NAO_INFORMADA = 56,
  ERRO_INESPERADO_GERANDO_TOKEN = 57,
  TRANSACAO_RECORRENTE_INVALIDA = 61,
  XID_NAO_FORNECIDO = 77,
  CAVV_NAO_FORNECIDO = 78,
  XID_E_CAV_NAO_FORNECIDOS = 86,
  CAVV_COM_TAMANHO_DIVERGENTE = 87,
  XID_COM_TAMANHO_DIVERGENTE = 88,
  ECI_COM_TAMANHO_DIVERGENTE = 89,
  ECI_INVALIDO = 90,
  ERRO_INTERNO_AUTENTICACAO = 95,
  SISTEMA_INDISPONIVEL = 97,
  TIMEOUT = 98,
  ERRO_INESPERADO = 99
}

export interface IErro {
  /**
  * Código do erro.
  */
  codigo: EnumCodigoErro,
  /**
  * Informações adicionais acerca do erro.
  */
  mensagem: string;
}
